const fs = require("fs")
const keywords = [
  "frankiedale4you",
  "ninachase52",
  "po_chf",
  "wally9519",
  "fineass_tk",
  "jteaseee",
  "oh_thatsro",
  "miggzsenor",
  "twitter aleahtweetie_",
  "illbeyourocean",
  "nalvaney",
  "melektemiizz",
  "formularenee",
  "azreecine",
  "astoryofamonkey",
  "knobendrs",
  "filacciano_vs",
  "wiseguycapital",
  "kinkyfishxxx",
  "kickinit_erica",
  "flan_lex",
  "ainlleb",
  "yamimatoy",
  "newsfromehughes",
  "mapule_xx",
  "xliishaa_x",
  "omgizmina",
  "slimm_kayy",
  "slushbuckles",
  "potneb",
  "morenosteez",
  "lyssapap",
  "vmungary",
  "ayyeejohannna",
  "wwg1wg",
  "forzaslan57 twitter",
  "alterbagets",
  "vinhk_nguyen",
  "kindra_badd",
  "robrahnrox",
  "blacklit101",
  "ultshadownsfw",
  "imfuture10",
  "m0btactics",
  "lievlaai",
  "mermaiidface",
  "pandangie20",
  "itskirstieann",
  "haechan",
  "lionellysdv",
  "berkinanc2",
  "sourkrause23",
  "rycielicious twitter",
  "watbtv",
  "fzhmida",
  "ritotosh insta",
  "kgandy_life",
  "iguess_nott",
  "skeeprofit",
  "invertals",
  "lexi2lit",
  "heybaah",
  "hernamels",
  "investtracing",
  "lilitkis",
  "xoxcassierose",
  "alberlitoo",
  "lulwahbr_",
  "channenwetrust",
  "lilruskin twitter",
  "อิแด๊ด น้องโร้ค",
  "gabrielleeeac",
  "akfamradio1",
  "mmerafinaa",
  "obeyy_aj",
  "toparol",
  "frostedmacdonut",
  "the_savzilla",
  "goyvrdlui",
  "cabellofckme",
  "ivorykeyona",
  "tyylerrrjane_",
  "wwg1gwga",
  "sa3don_95",
  "suwaidirey",
  "cwmffmr_w",
  "briromero77",
  "s8nsbabygirl",
  "cashmastermatt3",
  "carliiha22",
  "avaluvsuxo",
  "brats4cash",
  "atahir60",
  "paytontaylor_xo",
  "newyawnsday",
  "ydayifup",
  "annieraee_",
  "utkunall",
  "itzgabyb1tch",
  "kenferny",
  "haaleeighh",
  "nikkyourfav",
  "mrsjenbaby88",
  "waffurukuru",
  "vaaltoocracken",
  "leaflee",
  "ieujessica",
  "tweeter_lesley",
  "pausliebre",
  "doccmartin",
  "cretehashimnow",
  "sammyatt98",
  "andy61746329",
  "sffranwr",
  "nimo81",
  "iamnotshayla",
  "maddymills25",
  "theefaguette",
  "mathspd",
  "jessx_ippolito",
  "rohhse",
  "jondavidhd",
  "kmcvq",
  "coffeebaeee",
  "jesssboland",
  "ceoofemokids",
  "bigfifayones",
  "vrslano",
  "elledoole",
  "natxaxd",
  "macafigaari",
  "eminerkn_",
  "kathrynmac1118",
  "jjjasmeme",
  "mrstealurauntie",
  "harveyvore_",
  "jozeksey",
  "nirunul",
  "jayc2818",
  "nmrumorsandtea",
  "postsue1",
  "attemptingbutch",
  "jaaaaddee12",
  "mightycesarr",
  "macnpinkttv",
  "thegabafool",
  "leanne_greeneyes twitter",
  "nolistofthings",
  "mehaksamazing",
  "acmvampress",
  "y1n9y1n9",
  "severamargada",
  "dillon6736",
  "johnsgrowth",
  "thechanelrenee",
  "hookeronphonics",
  "https://twitter.com/rj71347659",
  "valeriiaa_7",
  "nikkittrann",
  "cohenisblowin",
  "h4lloween_queen",
  "ssuveeyda",
  "iplay_tumuch",
  "jxgzrxnu",
  "oonco",
  "phoebeus14",
  "biancaabooo",
  "esilayizmr",
  "titonton_fwe",
  "bbwfoxes",
  "goawayx0",
  "absvilleda",
  "peppersinsuat",
  "ladymargdolyn",
  "asiyakimbry",
  "dhavvv35",
  "tatsnkonzo",
  "stayceeee1",
  "attencian",
  "arrsso",
  "jadereeder4",
  "kassmcx",
  "lexussreneee",
  "bbrunch69",
  "cockmurdock",
  "juhleya",
  "aroobaaaaaa",
  "totalseasons",
  "k4devildogs",
  "beratadas1",
  "zehraabarr twitter",
  "kentileverbeam",
  "cashmeet",
  "channelstheapp",
  "foxynickvip",
  "sarabelton5",
  "cricinfomer",
  "maarianajuarezz",
  "cindye102 twitter",
  "naughtymomma401",
  "utiskore",
  "wwg1wea",
  "missmad220",
  "oldirtymelz",
  "missluluwolff",
  "msmiranduhs",
  "elliescanlan7",
  "karuzol",
  "ferrfacekilla",
  "ashlanglais",
  "emstrnns",
  "honeybeejimin",
  "ricczep",
  "carlosalba99",
  "mrknedy",
  "siyarati",
  "shawnriannebl",
  "itstotallyzeena",
  "jjbird888",
  "baemaltyyy",
  "dtfxxx2",
  "xoxbriellee",
  "punyahobi88",
  "smittyrog",
  "cjchavez112",
  "sstegemeyer",
  "dollmiinks",
  "fahazhan10",
  "farahnuwar",
  "20marquesa",
  "calph7",
  "imtoolazyokay",
  "abtchv",
  "elianaa_10",
  "afghanshawtyy",
  "therealmrexotic",
  "merebuttwhy",
  "rettinol",
  "natsur24",
  "rubyyjass",
  "johnmacias86",
  "arkanicide",
  "wardinablqis",
  "kittieslikepie",
  "melissacardonax",
  "acrs_director",
  "ava_ustina",
  "zombijen",
  "bristoliver",
  "philbaz12",
  "janae_page13",
  "7dirtyslots",
  "jason_jehu",
  "tinkteagyx",
  "rocketonyahead",
  "vegaslifetiara",
  "يارفيقي خاطري ماش وافكاري شتات",
  "avocadelie",
  "yun_nazira",
  "sinemkayramutlu",
  "mitchwill94",
  "motita_on_deck",
  "slaycyyn",
  "badgirlsvids",
  "firelordelmo",
  "funksta714",
  "cyashaavianna",
  "sgketsiou",
  "bagets pachupa",
  "ladelawhy",
  "amantasamazing",
  "tamizhsigma",
  "kaysupertramp",
  "ellielake05",
  "paroksham",
  "cezz666",
  "kimxpvlomo",
  "zzawahid",
  "rocki3h",
  "itsnotadelyo",
  "eeilidhh",
  "aceninjah1",
  "reynolljr18",
  "fortnitetracke4",
  "pappawatson",
  "indigcababy",
  "rooheykay",
  "karelialinzan",
  "fcbarcelonafl",
  "jammaax3",
  "zznatalyzz",
  "mata_temi",
  "puddyls twitter",
  "elitabethxx",
  "jacquelinemva",
  "goawaymk",
  "thediassnow",
  "comfibear",
  "keeleydontcare",
  "keaokapehu",
  "aranotang",
  "hvwendy22",
  "missnovaxx",
  "daisyxlaine",
  "cumeating",
  "boujeesav",
  "naomikessler8",
  "lastwordforum",
  "ilovemecmarie twitter",
  "grizzlygamerdev",
  "nyssaa03",
  "mikewarnersmg",
  "itskeyanahoe",
  "goldenwomaan",
  "lindslingerland",
  "vbustaaa",
  "justmaripok",
  "yungsquidback",
  "ruthpiperlilley",
  "mfjazc",
  "vote_4_paigero",
  "tsumetaigoon",
  "miguelgodinho99",
  "twitter loulaalkaff",
  "bbybree__",
  "farahouf_",
  "cnav122513",
  "nsenokwane",
  "theefaguette",
  "acr0827",
  "ohemaacindss",
  "nidimitrakis",
  "shakeshouka",
  "moviesd0tcom",
  "rupadrasta",
  "motivatefenty",
  "prostgrad",
  "wekura",
  "notstandingwith",
  "silaozc",
  "vegbarbie",
  "prawitaa",
  "superluckeee twitter",
  "iceprincesss17",
  "pushaxtea",
  "caravanforum",
  "น้องโร้คกับแด๊ด",
  "lizestrada346",
  "stardustetoile",
  "whoisriii",
  "ethaaari",
  "libmob",
  "edummo",
  "patribj99",
  "galileaxo",
  "eatmyiii_tweet",
  "jxsswhite",
  "carmen_past99",
  "yazzmelero",
  "jacindss",
  "beagleworld3",
  "joysamcyborg",
  "iamnikkiraexo",
  "chrisbstation",
  "stalesonnen",
  "vivalabueno",
  "wavydrugs",
  "ayoo_anto",
  "“hpm1210_1130raster.bundle” will damage your computer.",
  "pohug",
  "aerialink",
  "misskorealia",
  "udit7801",
  "nastexobby",
  "beth_harro",
  "dnlllynnp",
  "mirandajjjj_02",
  "gh0bbs16",
  "xtina_maria7",
  "meanmissqueen",
  "animarillika",
  "ceoniyah",
  "vamosankit",
  "barbiexoxo___",
  "seasie731",
  "frosted aline",
  "srksgeet",
  "wvrldwo",
  "ohlalaleahhh",
  "indianmenonline",
  "fashionistaaxo",
  "puddyls wetting",
  "#bethoc61",
  "vaanessatwitch",
  "helpitzlana",
  "onlinejsell",
  "honeymunnymoon",
  "sayplsbaby",
  "luckeee stocktwits",
  "tot7o3",
  "monicesweetfeet",
  "siarramayy",
  "sundeepgummadi",
  "wingyithepoon",
  "rebecay01",
  "enqxo",
  "hashinshin alice",
  "katrinahvel",
  "mistressmilly3",
  "leslieeeekarina",
  "sadgalkorie",
  "#alterbagets",
  "badbitchems",
  "jondavidhd",
  "laurenhulsey96",
  "twitter exoticaslim",
  "17fern38",
  "mirandaxo2",
  "arkadiem",
  "elfsexer69",
  "saltydoesnsfw",
  "tuestbellee",
  "gassylibrarian",
  "somis_pac96",
  "xshlyj",
  "mylostamygdala",
  "lhtskn",
  "wankbattle",
  "barbiexoxo___",
  "azita thorne",
  "giantessnyx",
  "cubanaf420",
  "rosiemankilla",
  "sinthiiaa3",
  "kaelladakilla",
  "glamprinny",
  "theafghanheart",
  "socialcareofferup.com",
  "ksmith2332",
  "tphantom202",
  "fineassdiorrr",
  "jessiprincey",
  "michellexzc",
  "sebbosch13",
  "swesex",
  "#alterpampanga",
  "egypt1327",
  "achor32020",
  "laurenseegz",
  "humanteddybear1",
  "slummamii",
  "cometson_sally",
  "cinnamoro11",
  "chubbrubb0921",
  "clothingdealsgb",
  "cashfags",
  "anon_bhr_cpl",
  "unde4dban",
  "hoessay4",
  "litojakolito",
  "rriissaa000",
  "babyyjoccy",
  "basicbuki",
  "wigsarcastictea",
  "wwg1wgo",
  "wwga1wga meaning",
  "keekz01",
  "dateeveyonyx",
  "spitinmymouthx",
  "punkaphrodite",
  "trishaxdiaz",
  "ggluvsyou669",
  "izzyanrubio",
  "applepigeon_",
  "me in 2066 after they announce the 76th lockdown",
  "nislatio",
  "imerika_jade",
  "s0bbing4lyfe",
  "exhibitionism8",
  "djspookykizzy",
  "krissy76luvbbc",
  "feguruguru",
  "kiksext",
  "egirltetona",
  "lilcookiewhore",
  "findomfarah",
  "gimmiegigixoxo",
  "roisinkatekelly",
  "niccvallee",
  "slave4cash",
  "jjjayjess",
  "kenzie50",
  "niji_chitsu",
  "masterted41",
  "yourcutegoddess",
  "citibe",
  "sarahcarr08",
  "godessmonet1",
  "neilbecks23",
  "kellydatoes",
  "astreliz",
  "jakolerongbata",
  "kimrojaas",
  "rowwvine",
  "keniaitzelp",
  "feetofbunnyxx",
  "ninaabiitch",
  "#sbfbu",
  "yayakirishima",
  "sinfinamondo",
  "cxxxlx",
  "msfikkity",
  "realzadity",
  "lycrastee",
  "sultry_nicole",
  "rntshr",
  "lilyrose006",
  "homoreligiosis",
  "ceohousingops",
  "fallonstarxxx",
  "derek_xcv",
  "movies2k2",
  "fancyaloevera",
  "#wwg1wg",
  "p1nkpr1ncesa dog",
  "talietaventura",
  "kinkyesme22",
  "vfsxx",
  "incelkai",
  "falseseke",
  "lilbambiqueen",
  "arileatherhead",
  "وفاة تلو وفاة اللهم لا تفجعني",
  "cherryhorrorx",
  "lillyarteagaxo",
  "goawaywendy",
  "aycaliiii",
  "beccaleegilbert",
  "kam2cold",
  "linksetan",
  "annie22551",
  "haruwinn7",
  "afghanshawty onlyfans",
  "muggledalal",
  "nudedude222",
  "jacdecnew",
  "findomitalia",
  "heelsandcuffs",
  "stardust_fawn",
  "2ninichan2",
  "spitinmymouthxx",
  "ferditsc",
  "babyboo94545",
  "mrknedy",
  "bitencourtgabs",
  "kayytamm",
  "bigneek617",
  "rvvvhel",
  "bchloe92",
  "laexoticamati",
  "wvrldwo sex",
  "luckeeebloomgmail.com",
  "19ne_",
  "niyah2bad",
  "jayfigs leaked",
  "shaughnyy_",
  "alephile",
  "rosedancer7700",
  "carnivalous walt",
  "frostedaline ass",
  "missynelson66",
  "tuestbellee",
  "tat2jacub",
  "mai3ddie",
  "musclegodmarcu1",
  "kyxlunna",
  "fmlzombies",
  "findomqueen_x",
  "19cneal",
  "elizabeth88onl1",
  "violentsinner",
  "mike_onenonly",
  "gothgurl626",
  "dudeitssofie",
  "tatithedub",
  "goldenmistresss",
  "jamieleepinky",
  "lexappeal33",
  "open bo semarang cod include",
  "swesex",
  "musclegodjay twitter",
  "quackanon",
  "thesnowbunnygo1",
  "h4ckerrogue",
  "soulsxcker",
  "helpitzlana onlyfans",
  "hetherrfortune",
  "breebaddyy",
  "clevernamexo",
  "superluckeee reviews",
  "muzvo",
  "vicspedro",
  "mistressofcont2",
  "im_to0ch",
  "queenklein218",
  "datwerg",
  "chloe_demesa twitter",
  "babybandza",
  "acedominant69",
  "ashesofpandora",
  "9japrime",
  "afghanshawtyy onlyfans",
  "feetseeguy",
  "truckstopghost",
  "heytherejanel onlyfans",
  "justrach0",
  "missynelson66 twitter",
  "sugaithkiut",
  "sentona97",
  "spacecadetkylee",
  "breeannaxxxx",
  "frosteddaliine",
  "jessica yaniv meow mix",
  "beccscohen",
  "sakshixs",
  "bpaulineeee",
  "babyfufu2",
  "claudiamua1",
  "tayylorrosse",
  "bzabzaza",
  "chupa bagets",
  "frostedaline booty",
  "atcshop",
  "cxvrtnzy twitter",
  "jholla_4",
  "rubratings little rock",
  "jillofsandwich",
  "fotune88",
  "alexandrawbu1",
  "habitixo",
  "zendikarbot_en",
  "lisam60609",
  "jaketyler51",
  "therealmrexotic sex",
  "baker4810",
  "tommytaylorxxx",
  "itsbabygirld",
  "lilpandajack",
  "savvshea",
  "open bo semarang cod",
  "lyndsmcdee",
  "daks bagets",
  "wndrlustxsoul",
  "egirltetona onlyfans",
  "what does wwga1wga mean",
  "keylaterrazas",
  "xprod_arab",
  "afgan shawty",
  "devonluxx",
  "writerjonallen",
  "availdepok",
  "nymphokyka",
  "olutobii",
  "spendonserenity",
  "atija zukauskaite",
  "ehoetional",
  "princessirene99",
  "electronicwiz1",
  "allie0t",
  "murrtube",
  "vfwineland",
  "sarratonin",
  "kaelhoney",
  "brialexandria13",
  "afghanshawty instagram",
  "brauuubs",
  "fendom app",
  "bunny_milf twitter",
  "mtotheholmes",
  "hhaileymitchell",
  "ella taclas",
  "yellataughtyou",
  "detoutebeauute",
  "blu7ohnny",
  "sakyubasux",
  "liabronjames",
  "kylakingg",
  "mkb941",
  "pixiv",
  "nychaftiel",
  "19biaaandrade",
  "availsemarang",
  "bbwpaigetampa",
  "suciosolis",
  "0345 3511692",
  "goddjessx",
  "hanaddo1",
  "linaleannz",
  "signoresamet",
  "goldenmistresss",
  "privateliaisons",
  "dyanaazriel",
  "frostedalone",
  "rmenezxo",
  "victoriapaigeza",
  "bispakjogja",
  "chef smera",
  "xwndrlustxsoul",
  "hrnysiutxo",
  "missrushdi",
  "aahbreel",
  "servemissmegan",
  "eatmyphannnie",
  "mississippitity",
  "bowdown2chelsea twitter",
  "lexi2legit pics",
  "いつだって僕らは フル ノクチル",
  "memeorite",
  "ケモレス",
]

const async = require("async")
const puppeteerGoogleScraper = require("puppeteer-google-scraper")
async.eachSeries(
  keywords,
  function(element, callback) {
    puppeteerGoogleScraper(element, {
      limit: 5,
      headless: true,
    }).then(d => {
      console.log(element, d)
      callback()
      fs.writeFile(
        "./src/content/" + element + ".md",
        `---
title: ${element}
description: Top ${element} adult content creator 👁♐️ 👑 subscribe ${element} to my porn site below IG ${element}
date: 2019-08-26
path: /${element}
---

${element}
${JSON.stringify(d)}

`,
        function(err) {}
      )
    })
  },
  function(err) {}
)
